name: Pull Request
description: Create a new pull request.
title: "[Pull Request for]: "
labels: ["pull request"]
body:
  - type: textarea
    id: Proposed changes
    attributes:
      label: "Description"
      description: Please enter an explicit description of your pull request
      placeholder: Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug, resolves a feature request or update documentation.
    validations:
      required: true
  - type: checkboxes
    id: Types of changes
    attributes:
      label: "Types of changes"
      description: What types of changes you made in this pull request?
      options:
        - label: "Bugfix (non-breaking change which fixes an issue)"
          required: false
        - label: "New feature (non-breaking change which adds functionality)"
          required: false
        - label: "Breaking change (fix or feature that would cause existing functionality to not work as expected)"
          required: false
        - label: "Documentation Update (if none of the other choices apply)"
          required: false
    validations:
      required: true
  - type: checkboxes
    id: Checklist
    attributes:
      label: "Checklist"
      description: "Please check if your PR fulfills the following requirements:"
      options:
        - label: "My code follows the code style of this project."
          required: true
        - label: "My change match with the documentation."
          required: true
        - label: "I have updated the documentation accordingly with the convention."
          required: true
        - label: "I have checked the typo of my document or commentary."
          required: true
        - label: "I have added tests to cover my changes."
          required: true
        - label: "All new and existing tests passed."
          required: true
    validations:
      required: true
  - type: textarea
    id: Further comments
    attributes:
      label: "Further comments"
      description: If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
      placeholder: Write your comments here...
    validations:
      required: false